// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define SDI_myApp_Admin_BODY

/************************************************************
 Admin class body
 ************************************************************/

// include associated header file
#include "SDI/myApp/Admin.h"

// Derived includes directives

namespace SDI {
namespace myApp {

// static attributes (if any)

/**
 * 
 * @param User 
 */
void Admin::AddModerator(User /*in*/User) {
}

/**
 * 
 * @param User 
 */
void Admin::RemoveModerator(User /*in*/User) {
}

/**
 * 
 * @param User 
 */
void Admin::ChangeAdmin(User /*in*/User) {
}

} // of namespace myApp
} // of namespace SDI

/************************************************************
 End of Admin class body
 ************************************************************/
