// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef SDI_MYAPP_CHANNEL_H
#define SDI_MYAPP_CHANNEL_H

/************************************************************
 Channel class header
 ************************************************************/

#include "SDI/myApp/Pkg_myApp.h"

#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"

namespace SDI {
namespace myApp {
class Message;
}
}

namespace SDI {
namespace myApp {

/************************************************************/
/**
 * 
 */
class Channel {
public:

	/**
	 * 
	 */
	::PrimitiveTypes::String Description;

	/**
	 * 
	 */
	Channel aChannel;

	/**
	 * 
	 * @param Title 
	 */
	void ChangeTitle(::PrimitiveTypes::String /*in*/Title = null);

	/**
	 * 
	 * @param Desc 
	 */
	void ChangeDescription(::PrimitiveTypes::String /*in*/Desc);

	/**
	 * 
	 * @param NewMessage 
	 */
	void SendMessage(Message /*in*/NewMessage);

	/**
	 * 
	 * @return ChannelTitle 
	 */
	::PrimitiveTypes::String GetTitle();

	/**
	 * 
	 * @return Description 
	 */
	::PrimitiveTypes::String GetDescription();

	/**
	 * 
	 * @param Message 
	 */
	void DeleteMessage(Message /*in*/Message);

	/**
	 * 
	 */
	void SubscribeToChannel();

	/**
	 * 
	 */
	void UnSubscribeFromChannel();

protected:

	/**
	 * 
	 */
	::PrimitiveTypes::String ChatRoomTitle;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace myApp
} // of namespace SDI

/************************************************************
 End of Channel class header
 ************************************************************/

#endif
