// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef SDI_MYAPP_IMAGE_H
#define SDI_MYAPP_IMAGE_H

/************************************************************
 Image class header
 ************************************************************/

#include "SDI/myApp/Pkg_myApp.h"

#include "SDI/myApp/Media.h"

namespace SDI {
namespace myApp {

/************************************************************/
/**
 * 
 */
class Image: public Media {
public:

	/**
	 * 
	 */
	void View();

	/**
	 * 
	 */
	void Get();

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace myApp
} // of namespace SDI

/************************************************************
 End of Image class header
 ************************************************************/

#endif
