// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define SDI_myApp_Room_BODY

/************************************************************
 Room class body
 ************************************************************/

// include associated header file
#include "SDI/myApp/Room.h"

// Derived includes directives

namespace SDI {
namespace myApp {

// static attributes (if any)

/**
 * 
 */
void Room::ChangeName() {
}

/**
 * 
 */
void Room::GetName() {
}

/**
 * 
 */
void Room::GetDescription() {
}

/**
 * 
 */
void Room::GetRoomID() {
}

/**
 * 
 */
void Room::GetMembers() {
}

} // of namespace myApp
} // of namespace SDI

/************************************************************
 End of Room class body
 ************************************************************/
