// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef SDI_MYAPP_VIDEO_H
#define SDI_MYAPP_VIDEO_H

/************************************************************
 Video class header
 ************************************************************/

#include "SDI/myApp/Pkg_myApp.h"

#include "SDI/myApp/Media.h"

namespace SDI {
namespace myApp {

/************************************************************/
/**
 * 
 */
class Video: public Media {
public:

	/**
	 * 
	 */
	void Play();

	/**
	 * 
	 */
	void Stop();

	/**
	 * 
	 */
	void Load();

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace myApp
} // of namespace SDI

/************************************************************
 End of Video class header
 ************************************************************/

#endif
