// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef SDI_MYAPP_MESSAGE_H
#define SDI_MYAPP_MESSAGE_H

/************************************************************
 Message class header
 ************************************************************/

#include "SDI/myApp/Pkg_myApp.h"

#include "EcorePrimitiveTypes/Pkg_EcorePrimitiveTypes.h"
#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"
#include "SDI/myApp/User.h"

namespace SDI {
namespace myApp {

/************************************************************/
/**
 * 
 */
class Message {
public:

	/**
	 * 
	 */
	::PrimitiveTypes::String MessageContent;

	/**
	 * 
	 */
	EDate TimeStamp;

	/**
	 * 
	 */
	Message aMessage;

	/**
	 * 
	 * @return Message 
	 */
	Message GetMessage();

	/**
	 * 
	 * @return CurrentDate 
	 */
	EDate GetDate();

	/**
	 * 
	 * @return Content 
	 */
	::PrimitiveTypes::String GetMessageContent();

protected:

	/**
	 * 
	 */
	static User User;

private:

	/**
	 * 
	 */
	::PrimitiveTypes::Integer RoomID;

	/**
	 * 
	 */
	undefined ChannelID;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace myApp
} // of namespace SDI

/************************************************************
 End of Message class header
 ************************************************************/

#endif
