// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define SDI_myApp_Message_BODY

/************************************************************
 Message class body
 ************************************************************/

// include associated header file
#include "SDI/myApp/Message.h"

// Derived includes directives

namespace SDI {
namespace myApp {

// static attributes (if any)
/**
 * 
 */
User Message::User;

/**
 * 
 * @return Message 
 */
Message Message::GetMessage() {
}

/**
 * 
 * @return CurrentDate 
 */
EDate Message::GetDate() {
}

/**
 * 
 * @return Content 
 */
::PrimitiveTypes::String Message::GetMessageContent() {
}

} // of namespace myApp
} // of namespace SDI

/************************************************************
 End of Message class body
 ************************************************************/
