// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define SDI_myApp_Moderator_BODY

/************************************************************
 Moderator class body
 ************************************************************/

// include associated header file
#include "SDI/myApp/Moderator.h"

// Derived includes directives

namespace SDI {
namespace myApp {

// static attributes (if any)

/**
 * 
 * @param User 
 */
void Moderator::AddUser(User /*in*/User) {
}

/**
 * 
 * @param User 
 */
void Moderator::RemoveUser(User /*in*/User) {
}

/**
 * 
 * @return Mod 
 */
User Moderator::GetUser() {
}

} // of namespace myApp
} // of namespace SDI

/************************************************************
 End of Moderator class body
 ************************************************************/
