// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef SDI_MYAPP_ADMIN_H
#define SDI_MYAPP_ADMIN_H

/************************************************************
 Admin class header
 ************************************************************/

#include "SDI/myApp/Pkg_myApp.h"

#include "SDI/myApp/User.h"

namespace SDI {
namespace myApp {

/************************************************************/
/**
 * 
 */
class Admin {
public:

	/**
	 * 
	 */
	User Admin;

private:

	/**
	 * 
	 * @param User 
	 */
	void AddModerator(User /*in*/User);

	/**
	 * 
	 * @param User 
	 */
	void RemoveModerator(User /*in*/User);

	/**
	 * 
	 * @param User 
	 */
	void ChangeAdmin(User /*in*/User);
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace myApp
} // of namespace SDI

/************************************************************
 End of Admin class header
 ************************************************************/

#endif
