// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define SDI_myApp_Image_BODY

/************************************************************
 Image class body
 ************************************************************/

// include associated header file
#include "SDI/myApp/Image.h"

// Derived includes directives

namespace SDI {
namespace myApp {

// static attributes (if any)

/**
 * 
 */
void Image::View() {
}

/**
 * 
 */
void Image::Get() {
}

} // of namespace myApp
} // of namespace SDI

/************************************************************
 End of Image class body
 ************************************************************/
