// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define SDI_myApp_Media_BODY

/************************************************************
 Media class body
 ************************************************************/

// include associated header file
#include "SDI/myApp/Media.h"

// Derived includes directives

namespace SDI {
namespace myApp {

// static attributes (if any)

/**
 * 
 */
void Media::Download() {
}

} // of namespace myApp
} // of namespace SDI

/************************************************************
 End of Media class body
 ************************************************************/
