// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef SDI_MYAPP_ROOM_H
#define SDI_MYAPP_ROOM_H

/************************************************************
 Room class header
 ************************************************************/

#include "SDI/myApp/Pkg_myApp.h"

#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"
#include "SDI/myApp/Channel.h"
#include "SDI/myApp/User.h"

namespace SDI {
namespace myApp {

/************************************************************/
/**
 * 
 */
class Room {
public:

	/**
	 * 
	 */
	::PrimitiveTypes::String Name;

	/**
	 * 
	 */
	Channel channel[];

	/**
	 * 
	 */
	::PrimitiveTypes::String Description;

	/**
	 * 
	 */
	Room aRoom;

	/**
	 * 
	 */
	::PrimitiveTypes::Integer RoomID;

	/**
	 * 
	 */
	void ChangeName();

	/**
	 * 
	 */
	void GetName();

	/**
	 * 
	 */
	void GetDescription();

	/**
	 * 
	 */
	void GetRoomID();

	/**
	 * 
	 */
	void GetMembers();

protected:

	/**
	 * 
	 */
	User Members[];

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace myApp
} // of namespace SDI

/************************************************************
 End of Room class header
 ************************************************************/

#endif
