// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef SDI_MYAPP_USER_H
#define SDI_MYAPP_USER_H

/************************************************************
 User class header
 ************************************************************/

#include "SDI/myApp/Pkg_myApp.h"

#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"

namespace SDI {
namespace myApp {
class Room;
}
}

namespace SDI {
namespace myApp {

/************************************************************/
/**
 * 
 */
class User {
public:

	/**
	 * 
	 */
	static ::PrimitiveTypes::String UserID;

	/**
	 * 
	 */
	::PrimitiveTypes::String Name;

	/**
	 * 
	 */
	::PrimitiveTypes::String Status;

	/**
	 * 
	 */
	::PrimitiveTypes::Boolean Online;

	/**
	 * 
	 */
	::PrimitiveTypes::String NickName;

	/**
	 * 
	 * @return NewName 
	 */
	::PrimitiveTypes::String ChangeName();

	/**
	 * 
	 * @param NewRoom 
	 */
	void SubscribeToRoom(Room /*in*/NewRoom);

	/**
	 * 
	 * @param OldRoom 
	 */
	void UnSubscribeToRoom(Room /*in*/OldRoom);

	/**
	 * 
	 * @return Name 
	 */
	::PrimitiveTypes::String GetName();

	/**
	 * 
	 * @return Status 
	 */
	::PrimitiveTypes::String GetStatus();

	/**
	 * 
	 * @return Status 
	 */
	::PrimitiveTypes::Boolean GetOnlineStat();

	/**
	 * 
	 * @return NickName 
	 */
	::PrimitiveTypes::String GetNickName();

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace myApp
} // of namespace SDI

/************************************************************
 End of User class header
 ************************************************************/

#endif
