// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define SDI_myApp_User_BODY

/************************************************************
 User class body
 ************************************************************/

// include associated header file
#include "SDI/myApp/User.h"

// Derived includes directives
#include "SDI/myApp/Room.h"

namespace SDI {
namespace myApp {

// static attributes (if any)
/**
 * 
 */
::PrimitiveTypes::String User::UserID;

/**
 * 
 * @return NewName 
 */
::PrimitiveTypes::String User::ChangeName() {
}

/**
 * 
 * @param NewRoom 
 */
void User::SubscribeToRoom(Room /*in*/NewRoom) {
}

/**
 * 
 * @param OldRoom 
 */
void User::UnSubscribeToRoom(Room /*in*/OldRoom) {
}

/**
 * 
 * @return Name 
 */
::PrimitiveTypes::String User::GetName() {
}

/**
 * 
 * @return Status 
 */
::PrimitiveTypes::String User::GetStatus() {
}

/**
 * 
 * @return Status 
 */
::PrimitiveTypes::Boolean User::GetOnlineStat() {
}

/**
 * 
 * @return NickName 
 */
::PrimitiveTypes::String User::GetNickName() {
}

} // of namespace myApp
} // of namespace SDI

/************************************************************
 End of User class body
 ************************************************************/
