// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define SDI_myApp_Video_BODY

/************************************************************
 Video class body
 ************************************************************/

// include associated header file
#include "SDI/myApp/Video.h"

// Derived includes directives

namespace SDI {
namespace myApp {

// static attributes (if any)

/**
 * 
 */
void Video::Play() {
}

/**
 * 
 */
void Video::Stop() {
}

/**
 * 
 */
void Video::Load() {
}

} // of namespace myApp
} // of namespace SDI

/************************************************************
 End of Video class body
 ************************************************************/
